/**
 * ======================================
 * PROG2005 Assignment 3
 * Add Item Page - Add + Featured (Tab 2)
 * Author: Bingru Song
 * ======================================
 *
 * Features:
 * - ReactiveForm for adding new inventory items
 * - Form validation with Validators
 * - Featured Items display section
 * - Toast feedback on submit
 * - Help Widget integration
 *
 * NOTE: This page is maintained by Bingru Song.
 * Core structure provided by Hanyu Man (whw343).
 */

import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { IonicModule } from '@ionic/angular';

import { ApiService } from '../../services/api.service';
import { Category, ItemFormData } from '../../models/inventory.model';
import { HelpWidgetComponent } from '../../components/help-widget/help-widget.component';

@Component({
  selector: 'app-add-item',
  templateUrl: './add-item.page.html',
  styleUrls: ['./add-item.page.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule,
    HelpWidgetComponent
  ],
})
export class AddItemPage implements OnInit {
  /** Reactive form for adding items */
  addItemForm!: FormGroup;

  /** Category options for dropdown */
  categories = Object.values(Category);

  /** Help widget content */
  helpContent = {
    title: 'Add Item Help',
    sections: [
      {
        heading: 'Adding Items',
        text: 'Fill in all required fields and tap "Add Item" to create a new inventory entry. The Item ID is auto-generated by the server.'
      },
      {
        heading: 'Featured Item',
        text: 'Set the Featured Item rating (0 = not featured, higher numbers = more prominently featured).'
      },
      {
        heading: 'Special Note',
        text: 'Optional field for additional notes about the item.'
      }
    ]
  };

  constructor(
    private fb: FormBuilder,
    public apiService: ApiService
  ) {}

  ngOnInit(): void {
    this.initForm();
  }

  /**
   * Initialize the Reactive Form with validation
   */
  private initForm(): void {
    this.addItemForm = this.fb.group({
      itemName: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(100)]],
      category: ['', Validators.required],
      quantity: [0, [Validators.required, Validators.min(0)]],
      price: [0.01, [Validators.required, Validators.min(0.01)]],
      supplierName: ['', [Validators.required, Validators.minLength(2)]],
      featuredItem: [0, [Validators.required, Validators.min(0)]],
      specialNote: ['']
    });
  }

  /**
   * Submit form to add a new item via API
   */
  onSubmit(): void {
    if (this.addItemForm.invalid) {
      this.addItemForm.markAllAsTouched();
      return;
    }

    const formData: ItemFormData = this.addItemForm.value;
    this.apiService.addItem(formData).subscribe({
      next: () => {
        this.addItemForm.reset({ quantity: 0, price: 0.01, featuredItem: 0 });
      },
      error: () => {
        // Error handled by ApiService
      }
    });
  }

  /**
   * Getter for form validation error messages
   */
  getErrorMessage(controlName: string): string {
    const control = this.addItemForm.get(controlName);
    if (!control || !control.errors || !control.touched) return '';

    if (control.errors['required']) return `${controlName} is required`;
    if (control.errors['minlength']) return `Minimum length: ${control.errors['minlength'].requiredLength}`;
    if (control.errors['maxlength']) return `Maximum length: ${control.errors['maxlength'].requiredLength}`;
    if (control.errors['min']) return `Minimum value: ${control.errors['min'].min}`;

    return 'Invalid input';
  }
}
