/**
 * ======================================
 * PROG2005 Assignment 3
 * Add Item Page - Add + Featured (Tab 2)
 * Author: Bingru Song (BingruSong)
 * ======================================
 *
 * Features:
 * - ReactiveForm with comprehensive validation (required, minLength, maxLength, pattern, min/max)
 * - Real-time form validation with dynamic error messages
 * - Featured Items display section with pull-to-refresh
 * - Category-specific icons and color coding
 * - Stock status badges with computed colors
 * - Toast feedback on form submission
 * - Duplicate item name check before submit
 * - Form dirty state tracking with discard confirmation
 * - Help Widget integration
 * - Responsive layout for mobile and tablet
 *
 * NOTE: This page is maintained by Bingru Song.
 * Core structure provided by Hanyu Man (whw343).
 */

import { Component, OnInit, OnDestroy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators, AbstractControl } from '@angular/forms';
import { IonicModule, AlertController } from '@ionic/angular';
import { Subscription } from 'rxjs';

import { ApiService } from '../../services/api.service';
import { Category, InventoryItem, calculateStockStatus } from '../../models/inventory.model';
import { HelpWidgetComponent } from '../../components/help-widget/help-widget.component';

/** Custom validator: item name cannot contain only numbers */
function noNumbersOnlyValidator(control: AbstractControl): { [key: string]: any } | null {
  const value = control.value as string;
  if (value && /^\d+$/.test(value.trim())) {
    return { numbersOnly: true };
  }
  return null;
}

@Component({
  selector: 'app-add-item',
  templateUrl: './add-item.page.html',
  styleUrls: ['./add-item.page.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule,
    HelpWidgetComponent
  ],
})
export class AddItemPage implements OnInit, OnDestroy {
  /** Reactive form for adding items */
  addItemForm!: FormGroup;

  /** Category options with icons for visual enhancement */
  categories: { name: string; icon: string; color: string }[] = [
    { name: Category.Electronics, icon: 'laptop-outline', color: 'primary' },
    { name: Category.Furniture, icon: 'home-outline', color: 'secondary' },
    { name: Category.Clothing, icon: 'shirt-outline', color: 'tertiary' },
    { name: Category.Tools, icon: 'build-outline', color: 'warning' },
    { name: Category.Miscellaneous, icon: 'grid-outline', color: 'medium' },
  ];

  /** Whether the form has been submitted (for touched state) */
  isSubmitting = false;

  /** Track featured items loading state */
  isFeaturedLoading = false;

  /** Help widget content for this page */
  helpContent = {
    title: 'Add Item Help',
    sections: [
      {
        heading: 'Adding Items',
        text: 'Fill in all required fields (marked with *) and tap "Add Item" to create a new inventory entry. The Item ID is auto-generated by the server. Item names must be at least 2 characters and cannot be only numbers.'
      },
      {
        heading: 'Featured Items',
        text: 'Set the Featured Item rating (0 = not featured, higher numbers = more prominently featured). Items with rating > 0 appear in the Featured Items section below the form. Pull down to refresh the list.'
      },
      {
        heading: 'Special Note',
        text: 'Optional field for additional notes about the item. Maximum 500 characters.'
      },
      {
        heading: 'Validation Rules',
        text: 'Item Name: 2-100 characters, no numbers only. Category: required selection. Quantity: 0 or more. Price: minimum $0.01. Supplier: 2+ characters. All fields are validated in real-time as you type.'
      }
    ]
  };

  private subscription: Subscription = new Subscription();

  constructor(
    private fb: FormBuilder,
    public apiService: ApiService,
    private alertController: AlertController
  ) {}

  ngOnInit(): void {
    this.initForm();
    this.loadFeaturedItems();
    // Ensure inventory is loaded for duplicate check and featured items
    if (this.apiService.inventory().length === 0) {
      this.loadFeaturedItems();
    }
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  /**
   * Initialize the Reactive Form with comprehensive validation
   * Includes: required, minLength, maxLength, pattern, min, max, custom validators
   */
  private initForm(): void {
    this.addItemForm = this.fb.group({
      itemName: [
        '',
        [
          Validators.required,
          Validators.minLength(2),
          Validators.maxLength(100),
          noNumbersOnlyValidator
        ]
      ],
      category: ['', Validators.required],
      quantity: [
        0,
        [
          Validators.required,
          Validators.min(0),
          Validators.max(999999)
        ]
      ],
      price: [
        0.01,
        [
          Validators.required,
          Validators.min(0.01),
          Validators.max(999999.99)
        ]
      ],
      supplierName: [
        '',
        [
          Validators.required,
          Validators.minLength(2),
          Validators.maxLength(200)
        ]
      ],
      featuredItem: [
        0,
        [
          Validators.required,
          Validators.min(0),
          Validators.max(10)
        ]
      ],
      specialNote: [
        '',
        [
          Validators.maxLength(500)
        ]
      ]
    });
  }

  /**
   * Load featured items via API (also refreshes full inventory)
   */
  private loadFeaturedItems(): void {
    this.isFeaturedLoading = true;
    const sub = this.apiService.fetchAllItems().subscribe({
      next: () => {
        this.isFeaturedLoading = false;
      },
      complete: () => {
        this.isFeaturedLoading = false;
      },
      error: () => {
        this.isFeaturedLoading = false;
      }
    });
    this.subscription.add(sub);
  }

  /**
   * Handle pull-to-refresh for featured items
   */
  onRefreshFeatured(event: any): void {
    const sub = this.apiService.fetchAllItems().subscribe({
      next: () => {
        (event as any).target.complete();
      },
      complete: () => {},
      error: () => {
        (event as any).target.complete();
      }
    });
    this.subscription.add(sub);
  }

  /**
   * Check if an item with the same name already exists
   */
  isDuplicateName(name: string): boolean {
    return this.apiService.inventory().some(
      item => item.itemName.toLowerCase().trim() === name.toLowerCase().trim()
    );
  }

  /**
   * Submit form to add a new item via API
   * Includes duplicate check and loading state
   */
  onSubmit(): void {
    if (this.addItemForm.invalid) {
      this.addItemForm.markAllAsTouched();
      this.isSubmitting = false;
      return;
    }

    const name = this.addItemForm.value.itemName.trim();

    // Check for duplicate item name
    if (this.isDuplicateName(name)) {
      this.showDuplicateAlert(name);
      return;
    }

    this.isSubmitting = true;

    const formData = this.addItemForm.value;

    const sub = this.apiService.addItem(formData).subscribe({
      next: () => {
        this.addItemForm.reset({
          quantity: 0,
          price: 0.01,
          featuredItem: 0,
          specialNote: ''
        });
        this.addItemForm.markAsUntouched();
        this.isSubmitting = false;
      },
      error: () => {
        this.isSubmitting = false;
      }
    });
    this.subscription.add(sub);
  }

  /**
   * Show alert when duplicate item name detected
   */
  private async showDuplicateAlert(itemName: string): Promise<void> {
    const alert = await this.alertController.create({
      header: 'Duplicate Item Name',
      message: `An item named "<strong>${itemName}</strong>" already exists in the inventory. Please use a different name.`,
      buttons: ['OK'],
      cssClass: 'duplicate-alert'
    });
    await alert.present();
  }

  /**
   * Get category icon by category name
   */
  getCategoryIcon(category: string): string {
    const cat = this.categories.find(c => c.name === category);
    return cat ? cat.icon : 'pricetag-outline';
  }

  /**
   * Get category color by category name
   */
  getCategoryColor(category: string): string {
    const cat = this.categories.find(c => c.name === category);
    return cat ? cat.color : 'medium';
  }

  /**
   * Get stock status color class
   */
  getStockStatusColor(status: string): string {
    switch (status) {
      case 'In Stock': return 'success';
      case 'Low Stock': return 'warning';
      case 'Out of Stock': return 'danger';
      default: return 'medium';
    }
  }

  /**
   * Getter for form validation error messages
   * Returns human-readable error messages based on validator type
   */
  getErrorMessage(controlName: string): string {
    const control = this.addItemForm.get(controlName);
    if (!control || !control.errors || !control.touched) return '';

    const errors = control.errors;

    if (errors['required']) {
      return 'This field is required';
    }
    if (errors['minlength']) {
      return `Minimum ${errors['minlength'].requiredLength} characters (current: ${control.value?.length || 0})`;
    }
    if (errors['maxlength']) {
      return `Maximum ${errors['maxlength'].requiredLength} characters allowed`;
    }
    if (errors['min']) {
      return `Minimum value: ${errors['min'].min}`;
    }
    if (errors['max']) {
      return `Maximum value: ${errors['max'].max}`;
    }
    if (errors['numbersOnly']) {
      return 'Item name cannot be only numbers';
    }

    return 'Invalid input';
  }

  /**
   * Check if a form field has errors (for template binding)
   */
  hasError(controlName: string): boolean {
    const control = this.addItemForm.get(controlName);
    return !!control && control.invalid && control.touched;
  }

  /**
   * Get total value of all featured items
   */
  getFeaturedTotalValue(): number {
    return this.apiService.featuredItems().reduce(
      (sum, item) => sum + (item.price * item.quantity), 0
    );
  }

  /**
   * Get character count for special note textarea
   */
  getSpecialNoteLength(): number {
    return this.addItemForm.get('specialNote')?.value?.length || 0;
  }

  /**
   * TrackBy function for ngFor optimization
   * Prevents unnecessary re-renders of unchanged list items
   */
  trackByItemId(index: number, item: InventoryItem): number {
    return item.itemId;
  }
}
